version = 1.0
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "weather-cat"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iasolxxv392z"
s3_prefix = "weather-cat"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
