AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  weather-cat

Globals:
  Function:
    Timeout: 5

Resources:
  WeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: weather-cat/
      Handler: weather-cat
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /weather
            Method: POST
      Environment:
        Variables:
          TEST_ENV: test
